### ISSUE TITLE
Issue with Java 8 in version 1+

### ISSUE THREAD

**Issue by adrianluan** [JodaOrg/joda-money#94]
Hi, 

Recently I updated the version in `app.gradle` from 0.12 to 1.0.1. However, it gave me an error when I built the project. 

`AGPBI: {"kind":"error","text":"Illegal class file: Class module-info is missing a super type.","sources":[{"file":"/Users/adrian/.gradle/caches/modules-2/files-2.1/org.joda/joda-money/1.0.1/dd4fc861d008d852abeb56994b603f33f7bd481a/joda-money-1.0.1.jar"}],"tool":"D8"}`

I did some research, realized this might be due to Java 8, so I added 
```
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
```

However, this caused an new error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Type without superclass: module-info
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visit(DefaultMethodClassFixer.java:80)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visit(InterfaceDesugaring.java:97)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:621)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)

:app:transformClassesWithDesugarForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
```

I am using JDK1.8 and SDK28

**Comment by jodastephen** [comment]
From Java 9 onwards, modules have been added, defined by `module-info.java`. The joda-money jar file is compatible with Java 8, but includes the relevant `module-info.class` file. This works fine in Java, but I assume you are using Android. You need to change your build to exclude the `module-info.class` file when performing the task `:app:transformClassesWithDesugarForDebug`.

I personally have no knowledge of that task or Android. You need to follow up with the authors of that task. It may be as simple as getting a new version of the task, adding config, or the task authors may need to write some code.
